// Mocks generated by Mockito 5.4.6 from annotations
// in car_maintenance_system_new/test/unit/booking_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:car_maintenance_system_new/features/booking/data/datasources/booking_remote_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BookingRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingRemoteDataSource extends _i1.Mock
    implements _i2.BookingRemoteDataSource {
  MockBookingRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> loadBookings({
    required String? userId,
    String? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadBookings,
          [],
          {
            #userId: userId,
            #role: role,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Stream<List<Map<String, dynamic>>> watchBookings({
    required String? userId,
    String? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchBookings,
          [],
          {
            #userId: userId,
            #role: role,
          },
        ),
        returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i3.Stream<List<Map<String, dynamic>>>);

  @override
  _i3.Future<String> createBooking(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBooking,
          [data],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #createBooking,
            [data],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updateBooking(
    String? bookingId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBooking,
          [
            bookingId,
            updates,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getBookingById(String? bookingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookingById,
          [bookingId],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> rateBooking({
    required String? bookingId,
    required double? rating,
    required String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rateBooking,
          [],
          {
            #bookingId: bookingId,
            #rating: rating,
            #comment: comment,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> processPayment({
    required String? bookingId,
    required String? cashierId,
    required String? paymentMethod,
    double? totalCost,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processPayment,
          [],
          {
            #bookingId: bookingId,
            #cashierId: cashierId,
            #paymentMethod: paymentMethod,
            #totalCost: totalCost,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
