/// Egyptian car market — makes and their available models
/// Sorted by popularity/prevalence in Egypt
class EgyptianCars {
  EgyptianCars._();

  /// All car makes available in Egypt
  static const List<String> makes = [
    'Toyota',
    'Hyundai',
    'Kia',
    'Nissan',
    'Chevrolet',
    'Mitsubishi',
    'Suzuki',
    'Honda',
    'Volkswagen',
    'Skoda',
    'SEAT',
    'MG',
    'Chery',
    'Geely',
    'BYD',
    'BAIC',
    'JAC',
    'Jetour',
    'Dongfeng',
    'Great Wall',
    'BMW',
    'Mercedes-Benz',
    'Audi',
    'Peugeot',
    'Renault',
    'Fiat',
    'Jeep',
    'Ford',
    'Mazda',
    'Lada',
  ];

  /// Models per make
  static const Map<String, List<String>> modelsByMake = {
    'Toyota': [
      'Corolla',
      'Camry',
      'Yaris',
      'Land Cruiser',
      'Land Cruiser Prado',
      'Fortuner',
      'Hilux',
      'RAV4',
      'C-HR',
      'Rush',
      'Avanza',
      'Prius',
      'Crown',
    ],
    'Hyundai': [
      'Elantra',
      'Tucson',
      'Accent',
      'Sonata',
      'Santa Fe',
      'Creta',
      'i10',
      'i20',
      'Kona',
      'Grand i10',
    ],
    'Kia': [
      'Cerato',
      'Sportage',
      'Picanto',
      'Rio',
      'K5',
      'Sorento',
      'Seltos',
      'Stonic',
      'Telluride',
      'Carnival',
    ],
    'Nissan': [
      'Sunny',
      'Sentra',
      'Tiida',
      'Qashqai',
      'X-Trail',
      'Patrol',
      'Pathfinder',
      'Kicks',
      'Juke',
      'Versa',
    ],
    'Chevrolet': [
      'Optra',
      'Aveo',
      'Cruze',
      'Captiva',
      'Spark',
      'Trax',
      'Equinox',
      'Traverse',
      'Tahoe',
    ],
    'Mitsubishi': [
      'Lancer',
      'Eclipse Cross',
      'Outlander',
      'Pajero',
      'L200',
      'ASX',
      'Attrage',
      'Xpander',
    ],
    'Suzuki': [
      'Swift',
      'Baleno',
      'Vitara',
      'S-Cross',
      'Celerio',
      'Ertiga',
      'Fronx',
    ],
    'Honda': [
      'Civic',
      'Accord',
      'HR-V',
      'CR-V',
      'City',
      'Jazz',
      'Pilot',
    ],
    'Volkswagen': [
      'Polo',
      'Golf',
      'Passat',
      'Tiguan',
      'Touareg',
      'Jetta',
      'T-Roc',
    ],
    'Skoda': [
      'Octavia',
      'Fabia',
      'Karoq',
      'Kodiaq',
      'Superb',
      'Kamiq',
    ],
    'SEAT': [
      'Ibiza',
      'Leon',
      'Ateca',
    ],
    'MG': [
      'MG5',
      'MG6',
      'MG ZS',
      'MG RX5',
      'MG HS',
      'MG GT',
      'MG3',
    ],
    'Chery': [
      'Tiggo 4',
      'Tiggo 7',
      'Tiggo 8',
      'Arrizo 5',
      'Arrizo 6',
    ],
    'Geely': [
      'Emgrand',
      'Coolray',
      'Tugella',
      'Okavango',
      'Preface',
    ],
    'BYD': [
      'Atto 3',
      'Han',
      'Song Plus',
      'Seal',
      'Dolphin',
    ],
    'BAIC': [
      'X35',
      'X55',
      'X7',
      'U5 Plus',
      'BJ40',
    ],
    'JAC': [
      'J7',
      'S4',
      'S3',
      'Sei4',
      'Sei6',
    ],
    'Jetour': [
      'X70',
      'X90',
      'X70 Plus',
      'Dashing',
    ],
    'Dongfeng': [
      'AX4',
      'AX7',
      'Box',
    ],
    'Great Wall': [
      'Haval H6',
      'Haval Jolion',
      'Haval H9',
      'Ora Good Cat',
    ],
    'BMW': [
      '116i',
      '118i',
      '120i',
      '218i',
      '316i',
      '318i',
      '320i',
      '328i',
      '418i',
      '420i',
      '520i',
      '523i',
      '528i',
      '730i',
      'X1',
      'X3',
      'X5',
      'X6',
    ],
    'Mercedes-Benz': [
      'A 180',
      'A 200',
      'C 200',
      'C 250',
      'E 200',
      'E 300',
      'S 400',
      'GLA 200',
      'GLC 200',
      'GLC 300',
      'GLE 400',
      'CLA 200',
    ],
    'Audi': [
      'A3',
      'A4',
      'A6',
      'Q3',
      'Q5',
      'Q7',
    ],
    'Peugeot': [
      '208',
      '301',
      '2008',
      '3008',
      '5008',
      '408',
    ],
    'Renault': [
      'Symbol',
      'Logan',
      'Duster',
      'Megane',
      'Fluence',
      'Kadjar',
      'Koleos',
    ],
    'Fiat': [
      '128',
      'Punto',
      'Tipo',
      '500X',
      'Bravo',
    ],
    'Jeep': [
      'Renegade',
      'Compass',
      'Cherokee',
      'Grand Cherokee',
      'Wrangler',
    ],
    'Ford': [
      'Fiesta',
      'Focus',
      'Fusion',
      'EcoSport',
      'Escape',
      'Edge',
      'Explorer',
      'F-150',
    ],
    'Mazda': [
      'Mazda2',
      'Mazda3',
      'Mazda6',
      'CX-3',
      'CX-30',
      'CX-5',
    ],
    'Lada': [
      'Vesta',
      'Granta',
      'Largus',
      'X-Ray',
    ],
  };

  /// Get models for a given make, returns empty list if make not found
  static List<String> modelsFor(String make) => modelsByMake[make] ?? [];

  /// Car colors common in Egypt
  static const List<String> colors = [
    'White',
    'Black',
    'Silver',
    'Gray',
    'Red',
    'Blue',
    'Beige',
    'Pearl',
    'Gold',
    'Bronze',
    'Green',
    'Orange',
  ];

  /// Generate list of years from 1990 to current year+1
  static List<int> get years {
    final currentYear = DateTime.now().year;
    return List.generate(currentYear - 1989, (i) => currentYear + 1 - i);
  }
}
