import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

final localeProvider = StateNotifierProvider<LocaleNotifier, Locale>((ref) {
  return LocaleNotifier();
});

class LocaleNotifier extends StateNotifier<Locale> {
  // Default to Arabic (Egyptian)
  LocaleNotifier() : super(const Locale('ar', 'EG')) {
    _loadLocale();
  }

  Future<void> _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final langCode = prefs.getString('language_code');
    if (langCode != null) {
      state = Locale(langCode);
    }
  }

  Future<void> setLocale(Locale locale) async {
    state = locale;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', locale.languageCode);
  }
}

class AppLocalizations {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'welcome': 'Welcome',
      'dashboard': 'Dashboard',
      'my_cars': 'My Cars',
      'offers': 'Offers',
      'chat': 'Chat',
      'profile': 'Profile',
      'settings': 'Settings',
      'settings_and_profile': 'Settings & Profile',
      'notifications': 'Notifications',
      'manage_offers': 'Manage Offers',
      'invite_codes': 'Invite Codes',
      'sign_out': 'Sign Out',
      'personal_information': 'Personal Information',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'email': 'Email',
      'save_profile': 'Save Profile',
      'appearance': 'Appearance',
      'theme_mode': 'Theme Mode',
      'language': 'Language',
      'app_language': 'App Language',
      'app_information': 'App Information',
      'help_support': 'Help & Support',
      'privacy_policy': 'Privacy Policy',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'how_can_we_help': 'How can we help you with your car today?',
      'quick_actions': 'Quick Actions',
      'upcoming_appointments': 'Upcoming Appointments',
      'are_you_sure_signout': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'save': 'Save',
      'chatbot_title': 'Smart Assistant',
      'online_now': 'Online Now',
      'clear_conversation': 'Clear Conversation',
      'tech_chatbot_welcome': 'Need Help?',
      'customer_chatbot_welcome': 'Hello! How can I help you?',
      'tech_chatbot_hint': 'Send me a photo of the issue or a diagnostic code and I will help you.',
      'customer_chatbot_hint': 'Ask me about our services, prices, or any other inquiry.',
      'active_services': 'Active Services',
      'payment_due': 'Payment Due',
      'total_amount': 'Total Amount',
      'technician_working': 'Our technician is working on your vehicle',
      'service_in_progress': 'Service in Progress',
      'service_completed': 'Service Completed',
      'regular_maintenance': 'Regular Maintenance',
      'repair_service': 'Repair Service',
      'inspection': 'Inspection',
      'emergency_service': 'Emergency Service',
      'account_created': 'Account created successfully! Redirecting...',
      'registration_failed': 'Registration failed. Please try again.',
      'create_account': 'Create Account',
      'join_car_maintenance': 'Join FixHub',
      'create_account_subtitle': 'Create your account to get started',
      'enter_name_validation': 'Please enter your name',
      'name_min_length': 'Name must be at least 2 characters',
      'invalid_email': 'Please enter a valid email',
      'enter_phone_validation': 'Please enter your phone number',
      'invalid_phone': 'Please enter a valid phone number',
      'customer_account': 'Customer Account',
      'customer_account_desc': 'Book services and manage your vehicles',
      'technician_account': 'Technician Account',
      'technician_account_desc': 'Requires an invite code from admin',
      'cashier_account': 'Cashier Account',
      'cashier_account_desc': 'Requires an invite code from admin',
      'invite_code': 'Invite Code *',
      'invite_code_hint': 'Enter the invite code provided by the administrator',
      'invite_code_required': 'Invite code is required for this account type',
      'invalid_invite_code': 'Invalid invite code format',
      'confirm_password': 'Confirm Password',
      'confirm_password_validation': 'Please confirm your password',
      'passwords_dont_match': 'Passwords do not match',
      'password_min_length': 'Password must be at least 6 characters',
      'already_have_account': 'Already have an account? ',
      'generate_invite_code': 'Generate New Invite Code',
      'role': 'Role',
      'technician': 'Technician',
      'cashier': 'Cashier',
      'admin': 'Admin',
      'max_uses': 'Max Uses',
      'generate_code': 'Generate Code',
      'generating': 'Generating...',
      'invalid_max_uses': 'Please enter a valid number for max uses',
      'invite_code_created': 'Invite code created: ',
      'copy': 'Copy',
      'code_copied': 'Code copied to clipboard!',
      'error_creating_code': 'Error creating invite code: ',
      'deactivate_users_title': 'Deactivate User Accounts?',
      'deactivate_users_desc': 'This code has been used by users. Do you want to deactivate their accounts as well?',
      'no': 'No',
      'yes_deactivate': 'Yes, Deactivate Users',
      'reactivate_users_title': 'Reactivate User Accounts?',
      'reactivate_users_desc': 'This code was used by users. Do you want to reactivate their accounts as well?',
      'yes_reactivate': 'Yes, Reactivate Users',
      'code_deactivated': 'Code deactivated',
      'code_activated': 'Code activated',
      'no_invite_codes': 'No invite codes yet',
      'generate_one_form': 'Generate one using the form above',
      'uses': 'Uses:',
      'used_by': 'Used by:',
      'loading': 'Loading...',
      'active': 'Active',
      'inactive': 'Inactive',
      'admin_dashboard': 'Admin Dashboard',
      'welcome_back': 'Welcome back, ',
      'business_overview': 'Here\'s what\'s happening with your business today.',
      'overview': 'Overview',
      'services': 'Services',
      'refunds': 'Refunds',
      'reports': 'Reports',
      'recent_activities': 'Recent Activities',
      'users': 'Users',
      'technicians_nav': 'Technicians',
      'bookings': 'Bookings',
      'analytics': 'Analytics',
      'total_users': 'Total Users',
      'active_bookings': 'Active Bookings',
      'completed_today': 'Completed Today',
      'total_revenue': 'Total Revenue',
      'currency': 'EGP',
      'no_recent_activities': 'No recent activities',
      'activities_appear_here': 'Activities will appear here as they happen',
      'new_booking': 'New Booking',
      'booking_created_for': 'Booking created for',
      'booking_confirmed': 'Booking Confirmed',
      'confirmed': 'confirmed',
      'is_being_serviced': 'is being serviced',
      'awaiting_payment': 'Awaiting Payment',
      'completed_waiting_payment': 'completed, waiting for payment',
      'was_cancelled': 'was cancelled',
      'days_ago': 'days ago',
      'hours_ago': 'hours ago',
      'minutes_ago': 'minutes ago',
      'just_now': 'Just now',
      'welcome_cashier': 'Welcome, ',
      'pending_payments': 'Pending Payments',
      'todays_total': 'Today\'s Total',
      'refunds_pending': 'Refunds Pending',
      'tap_to_process_refunds': 'Tap to process approved refunds',
      'view_all': 'View All',
      'no_pending_payments': 'No pending payments',
      'invoice': 'Invoice #',
      'customer': 'Customer: ',
      'amount': 'Amount: ',
      'completed_at': 'Completed: ',
      'receive': 'Receive',
      'payments_nav': 'Payments',
      'profile_nav': 'Profile',
      'payments': 'Payments',
      'pending': 'Pending',
      'completed': 'Completed',
      'no_completed_payments': 'No completed payments',
      'receive_payment': 'Receive Payment',
      'cash': 'Cash',
      'card': 'Credit Card',
      'digital_wallet': 'Digital Wallet',
      'invoice_details': 'Invoice Details',
      'export_invoice': 'Export Invoice',
      'error_exporting': 'Error exporting invoice: ',
      'payment_processed': 'Payment processed successfully!',
      'failed_payment': 'Failed to process payment',
      'booking_info': 'Booking Information',
      'invoice_number': 'Invoice Number',
      'vehicle': 'Vehicle',
      'completion_date': 'Completion Date',
      'discount_code': 'Discount Code',
      'offer_title': 'Offer Title',
      'discount_percentage': 'Discount %',
      'vehicle_details': 'Vehicle Details',
      'make': 'Make',
      'model': 'Model',
      'year': 'Year',
      'license_plate': 'License Plate',
      'color': 'Color',
      'type': 'Type',
      'vin': 'VIN',
      'mileage': 'Mileage',
      'engine_type': 'Engine Type',
      'parts_services': 'Parts & Services',
      'qty': 'Qty: ',
      'cost_breakdown': 'Cost Breakdown',
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'after_discount': 'After Discount',
      'discount_applied': 'Discount Applied',
      'code': 'Code: ',
      'labor_cost': 'Labor Cost',
      'tax': 'Tax (10%)',
      'total': 'Total',
      'payment_method': 'Payment Method',
      'confirm_payment': 'Confirm Payment Received',
      'processing': 'Processing...',
      'payment_completed': 'Payment Completed',
      'request_refund': 'Request Refund',
      'original_amount': 'Original Amount: ',
      'refund_amount': 'Refund Amount',
      'reason_refund': 'Reason for Refund *',
      'enter_reason': 'Enter reason for refund request',
      'submit_request': 'Submit Request',
      'please_enter_reason': 'Please enter a reason for the refund',
      'refund_submitted': 'Refund request submitted successfully',
      'refund_processed_notified': 'Refund processed - Customer notified',
      'phone_not_available': 'Phone number not available',
      'refund_details': 'Refund Details',
      'amount_to_refund': 'Amount to Refund',
      'processed_on': 'Processed on ',
      'requested': 'Requested: ',
      'confirm_refund': 'Confirm Refund',
      'confirm_refund_message': 'Please confirm that you have returned the money to the customer.',
      'yes_refund_completed': 'Yes, Refund Completed',
      'retry': 'Retry',
      'no_pending_refunds': 'No pending refunds',
      'close': 'Close',
      'process': 'Process',
      'reason': 'Reason',
      'notes': 'Notes',
      'financial_reports': 'Financial Reports',
      'export_csv': 'Export CSV',
      'today': 'Today',
      'last_7_days': 'Last 7 Days',
      'last_30_days': 'Last 30 Days',
      'all_time': 'All Time',
      'custom_range': 'Custom Range...',
      'all_time_report': 'All Time Report',
      'total_profit': 'Total Profit',
      'transactions': 'Transactions',
      'margin': 'margin',
      'creating_report': 'Creating Report...',
      'file_saved': 'File Saved',
      'csv_saved_successfully': 'CSV report has been saved successfully!',
      'location': 'Location:',
      'open_file': 'Open File',
      'no_payments_found': 'No payments found',
      'profit_margin': 'Profit Margin',
      'parts_cost': 'Parts Cost',
      'profit': 'Profit',
      'welcome_technician': 'Welcome, ',
      'ready_start_day': 'Ready to start your day?',
      'performance': 'Performance',
      'todays_jobs': "Today's Jobs",
      'jobs': 'Jobs',
      'ai_chat': 'AI Chat',
      'my_jobs': 'My Jobs',
      'no_jobs_assigned': 'No jobs assigned',
      'assigned_jobs_appear_here': 'Your assigned jobs will appear here',
      'continue_work_complete': 'Continue Work & Complete Job',
      'view_invoice': 'View Invoice',
      'start_job_add_invoice': 'Start Job & Add Invoice',
      'no_status_jobs': 'No jobs found',
      'job_details': 'Job Details',
      'complete_job': 'Complete Job',
      'started': 'Started: ',
      'completion_time': 'Completed: ',
      'hours_worked': 'Hours Worked: ',
      'service_items_parts': 'Service Items & Parts',
      'no_items_added': 'No items added yet',
      'add_item': 'Add Item',
      'save_progress': 'Save Progress',
      'start_job': 'Start Job',
      'job_started': 'Job started!',
      'failed_start_job': 'Failed to start job',
      'progress_saved': 'Progress saved!',
      'failed_save_progress': 'Failed to save progress',
      'please_add_item_labor': 'Please add at least one service item or labor cost',
      'job_completed_successfully': 'Job completed successfully!',
      'failed_complete_job': 'Failed to complete job',
      'add_items_to_invoice': 'Add Items to Invoice',
      'no_catalog_items': 'No catalog items available for this maintenance type.\nAsk admin to add services.',
      'add_selected': 'Add Selected',
      'unit': 'unit',
      'could_not_load_job': 'Could not load job details. Please try again.',
      'add': 'Add ',
      'items_count': ' Item(s)',
      'profile_updated': 'Profile updated successfully!',
      'error_updating_profile': 'Error updating profile: ',
      'jobs_completed': 'Jobs Completed',
      'member_since': 'Member Since',
      'saving': 'Saving...',
      'edit_information': 'Edit Information',
      'name_required': 'Name is required',
      'email_cannot_change': 'Email cannot be changed',
      'phone_required': 'Phone number is required',
      'sign_out_confirm': 'Are you sure you want to sign out?',
      'no_cars_registered': 'No cars registered yet',
      'add_first_car': 'Add your first car to get started',
      'add_car': 'Add Car',
      'delete_car_confirm': 'Are you sure you want to delete this car?',
      'car_deleted_successfully': 'Car deleted successfully',
      'failed_delete_car': 'Failed to delete car',
      'add_new_car': 'Add New Car',
      'car_make': 'Car Make',
      'select_brand': 'Select car brand',
      'select_brand_first': 'Select brand first',
      'select_model': 'Select model',
      'select_year': 'Select year',
      'select_color': 'Select color',
      'car_type': 'Car Type',
      'sedan': 'Sedan',
      'suv': 'SUV',
      'truck_pickup': 'Truck / Pickup',
      'hatchback': 'Hatchback',
      'coupe': 'Coupe',
      'van_minivan': 'Van / Minivan',
      'plate_number': 'Plate Number',
      'plate_number_hint': 'e.g., 123 أ ب ج',
      'car_added_successfully': 'Car added successfully!',
      'failed_add_car': 'Failed to add car',
      'select_brand_validation': 'Please select the car brand',
      'select_model_validation': 'Please select the model',
      'select_year_validation': 'Please select the year',
      'select_color_validation': 'Please select the color',
      'enter_plate_validation': 'Please enter plate number',
      'my_bookings': 'My Bookings',
      'no_bookings_yet': 'No bookings yet',
      'book_first_service': 'Book your first service',
      'cancel_booking': 'Cancel Booking',
      'cancel_booking_confirm': 'Are you sure you want to cancel this booking?',
      'booking_cancelled': 'Booking cancelled',
      'failed_cancel_booking': 'Failed to cancel booking',
      'select_your_car': 'Select Your Car',
      'add_another_car': 'Add another car',
      'maintenance_type': 'Maintenance Type',
      'appointment_date_time': 'Appointment Date & Time',
      'working_hours_desc': 'Working hours: Sat – Thu, 8:00 AM – 6:00 PM',
      'select_date': 'Select Date',
      'select_time': 'Select Time',
      'additional_notes': 'Additional Notes (Optional)',
      'describe_issue_hint': 'Describe your issue or any additional details…',
      'confirm_booking': 'Confirm Booking',
      'back': 'Back',
      'next': 'Next',
      'your_car': 'Your Car',
      'service': 'Service',
      'confirm': 'Confirm',
      'select_car_validation': 'Please select your car first',
      'select_maintenance_validation': 'Please select a maintenance type',
      'select_date_time_validation': 'Please select date and time',
      'closed_fridays': 'We are closed on Fridays',
      'booking_confirmed_success': 'Booking confirmed!',
      'select_date_first': 'Please select a date first',
      'working_hours_help': 'Working Hours: 8:00 AM – 6:00 PM',
      'select_time_range_validation': 'Please select a time between 8:00 AM and 6:00 PM',
      'enter_discount_code': 'Please enter a discount code',
      'select_date_help': 'Select Appointment Date (Closed Fridays)',
      'booking_summary': 'Booking Summary',
      'final_price_notice': 'Final price will be calculated after the technician completes the service',
      'discount_code_hint': 'Enter code (optional)',
      'apply': 'Apply',
      'discount_applied_desc': 'discount applied',
      'view_available_offers': 'View available offers',
      'regular_maintenance_hint': 'Oil change, filters, fluids…',
      'inspection_hint': 'Safety check, computer scan…',
      'repair_hint': 'Brakes, engine, transmission…',
      'emergency_hint': 'Urgent — off-road assistance…',
      'service_history': 'Service History',
      'total_spent': 'Total Spent',
      'no_service_history': 'No service history',
      'service_history_desc': 'Your service history will appear here',
      'total_cost_label': 'Total Cost:',
      'your_rating': 'Your Rating: ',
      'rate_this_service': 'Rate This Service',
      'rating_submitted': 'Rating submitted successfully!',
      'failed_rating': 'Failed to submit rating',
      'booking_id': 'Booking ID: ',
      'download_pdf': 'Download PDF',
      'add_car_subtitle': 'Register your vehicle',
      'book_service': 'Book Service',
      'book_service_subtitle': 'Schedule maintenance',
      'ai_assistant': 'AI Assistant',
      'ai_assistant_subtitle': 'Ask questions',
      'special_offers': 'Special Offers',
      'special_offers_subtitle': 'View deals & discounts',
      'service_history_subtitle': 'View past services',
      'my_cars_subtitle': 'Manage vehicles',
      'cancel_appointment': 'Cancel Appointment',
      'keep_appointment': 'Keep Appointment',
      'appointment_cancelled_success': 'Appointment cancelled successfully',
      'failed_cancel_appointment': 'Failed to cancel appointment. Please try again.',
      'cancel_appointment_confirm': 'Are you sure you want to cancel this appointment? This action cannot be undone.',
      'missed_appointments': 'Missed Appointments',
      'missed_appointments_desc': 'You missed these appointments. Please reschedule or cancel them.',
      'reschedule': 'Reschedule',
      'missed_status': 'MISSED',
      'was_scheduled': 'Was scheduled',
      'missed_ago': 'Missed',
      'day_ago': 'day ago',
      'hour_ago': 'hour ago',
      'days_only': 'days',
      'day_only': 'day',
      'hours_only': 'hours',
      'hour_only': 'hour',
      'recently': 'Recently',
      'offers_announcements': 'Offers & Announcements',
      'announcements': 'Announcements',
      'discounts': 'Discounts',
      'promotions': 'Promotions',
      'news': 'News',
      'no_offers_available': 'No offers available',
      'check_back_later_offers': 'Check back later for new offers!',
      'error_loading_offers': 'Error loading offers',
      'valid_from': 'Valid from',
      'expires': 'Expires',
      'valid_period': 'Valid Period:',
      'terms_conditions': 'Terms & Conditions:',
      'code_label': 'Code: ',
      'enter_code_booking_desc': 'Enter this code when booking to get the discount',
      'discount_off': 'OFF',
      'no_offers_type': 'No offers found',
      'profile_updated_success': 'Profile updated successfully!',

      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'code_deactivated_users_disabled': 'Code deactivated and user account(s) disabled',
      'code_activated_users_enabled': 'Code activated and user account(s) enabled',
      'not_used_yet': 'Not used yet',
      'error_loading_names': 'Error loading names',
      'delete_invite_code': 'Delete Invite Code',
      'delete_code_confirm': 'Are you sure you want to delete code: ',
      'code_deleted_success': 'Code deleted successfully',
      'error_deleting_code': 'Error deleting code: ',
      'deactivate': 'Deactivate',
      'activate': 'Activate',
    },
    'ar': {
      'welcome': 'أهلاً بيك',
      'dashboard': 'الرئيسية',
      'my_cars': 'عربياتي',
      'offers': 'العروض',
      'chat': 'المحادثة',
      'profile': 'البروفايل',
      'settings': 'الإعدادات',
      'settings_and_profile': 'الإعدادات والبروفايل',
      'notifications': 'الإشعارات',
      'manage_offers': 'إدارة العروض',
      'invite_codes': 'أكواد الدعوة',
      'sign_out': 'تسجيل خروج',
      'personal_information': 'البيانات الشخصية',
      'full_name': 'الاسم بالكامل',
      'phone_number': 'رقم التليفون',
      'email': 'الإيميل',
      'save_profile': 'حفظ البروفايل',
      'appearance': 'المظهر',
      'theme_mode': 'وضع الشاشة (مضيء/مظلم)',
      'language': 'اللغة',
      'app_language': 'لغة التطبيق',
      'app_information': 'معلومات عن التطبيق',
      'help_support': 'المساعدة والدعم',
      'privacy_policy': 'سياسة الخصوصية',
      'good_morning': 'صباح الفل',
      'good_afternoon': 'مساء الفل',
      'good_evening': 'مساء الفل',
      'how_can_we_help': 'نقدر نساعدك إزاي في عربيتك النهاردة؟',
      'quick_actions': 'إجراءات سريعة',
      'upcoming_appointments': 'حجوزاتك الجاية',
      'are_you_sure_signout': 'متأكد إنك عايز تعمل تسجيل خروج؟',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'chatbot_title': 'المساعد الذكي',
      'online_now': 'متصل الآن',
      'clear_conversation': 'مسح المحادثة',
      'tech_chatbot_welcome': 'محتار في إيه؟',
      'customer_chatbot_welcome': 'أهلاً بيك! أقدر أساعدك إزاي؟',
      'tech_chatbot_hint': 'ابعتلي صورة العطل أو كود الفحص وهساعدك في التشخيص والحل.',
      'customer_chatbot_hint': 'اسألني عن خدماتنا، أسعارنا، أو أي حاجة تانية تخص عربيتك.',
      'active_services': 'الخدمات الحالية',
      'payment_due': 'مطلوب الدفع',
      'total_amount': 'الإجمالي',
      'technician_working': 'الفني شغال في عربيتك دلوقتي',
      'service_in_progress': 'جاري العمل',
      'service_completed': 'الخدمة خلصت',
      'regular_maintenance': 'صيانة دورية',
      'repair_service': 'خدمة تصليح',
      'inspection': 'فحص',
      'emergency_service': 'طوارئ',
      'account_created': 'تم إنشاء الحساب بنجاح! جاري التوجيه...',
      'registration_failed': 'فشل إنشاء الحساب. برجاء المحاولة مرة أخرى.',
      'create_account': 'إنشاء حساب جديد',
      'join_car_maintenance': 'انضم لـ FixHub',
      'create_account_subtitle': 'اعمل حسابك دلوقتي عشان تبدأ',
      'enter_name_validation': 'برجاء إدخال اسمك',
      'name_min_length': 'الاسم لازم يكون أكتر من حرفين',
      'invalid_email': 'برجاء إدخال إيميل صحيح',
      'enter_phone_validation': 'برجاء إدخال رقم تليفونك',
      'invalid_phone': 'برجاء إدخال رقم تليفون صحيح',
      'customer_account': 'حساب عميل',
      'customer_account_desc': 'احجز خدمات وتابع عربياتك بسهولة',
      'technician_account': 'حساب فني',
      'technician_account_desc': 'محتاج كود دعوة من الإدارة',
      'cashier_account': 'حساب كاشير',
      'cashier_account_desc': 'محتاج كود دعوة من الإدارة',
      'invite_code': 'كود الدعوة *',
      'invite_code_hint': 'اكتب كود الدعوة اللي أخدته من الإدارة',
      'invite_code_required': 'كود الدعوة مطلوب للنوع ده من الحسابات',
      'invalid_invite_code': 'صيغة الكود غير صحيحة',
      'confirm_password': 'تأكيد الباسورد',
      'confirm_password_validation': 'برجاء تأكيد الباسورد',
      'passwords_dont_match': 'الباسورد مش متطابق',
      'password_min_length': 'الباسورد لازم يكون على الأقل 6 حروف',
      'already_have_account': 'عندك حساب بالفعل؟ ',
      'generate_invite_code': 'توليد كود دعوة جديد',
      'role': 'الوظيفة (Role)',
      'technician': 'فني',
      'cashier': 'كاشير',
      'admin': 'أدمن',
      'max_uses': 'أقصى عدد للاستخدام',
      'generate_code': 'إنشاء الكود',
      'generating': 'جاري الإنشاء...',
      'invalid_max_uses': 'برجاء إدخال رقم صحيح لعدد الاستخدامات',
      'invite_code_created': 'تم إنشاء كود الدعوة: ',
      'copy': 'نسخ',
      'code_copied': 'تم نسخ الكود!',
      'error_creating_code': 'حصل خطأ في إنشاء الكود: ',
      'deactivate_users_title': 'تعطيل حسابات المستخدمين؟',
      'deactivate_users_desc': 'الكود ده تم استخدامه قبل كده. عايز تعطل حساباتهم كمان؟',
      'no': 'لأ',
      'yes_deactivate': 'أيوه، عطل الحسابات',
      'reactivate_users_title': 'إعادة تفعيل حسابات المستخدمين؟',
      'reactivate_users_desc': 'الكود ده تم استخدامه. عايز تفعل حساباتهم تاني؟',
      'yes_reactivate': 'أيوه، فعل الحسابات',
      'code_deactivated': 'تم تعطيل الكود',
      'code_activated': 'تم تفعيل الكود',
      'no_invite_codes': 'مفيش أكواد دعوة لسه',
      'generate_one_form': 'اعمل كود جديد من الفورم اللي فوق',
      'uses': 'الاستخدام:',
      'used_by': 'تم استخدامه بواسطة:',
      'loading': 'جاري التحميل...',
      'active': 'نشط',
      'inactive': 'غير نشط',
      'admin_dashboard': 'لوحة تحكم الإدارة',
      'welcome_back': 'أهلاً بيك يا ',
      'business_overview': 'دي ملخص حالة الشغل النهاردة.',
      'overview': 'نظرة عامة',
      'services': 'الخدمات',
      'refunds': 'المرتجعات',
      'reports': 'التقارير',
      'recent_activities': 'أحدث النشاطات',
      'users': 'المستخدمين',
      'technicians_nav': 'الفنيين',
      'bookings': 'الحجوزات',
      'analytics': 'الإحصائيات',
      'total_users': 'إجمالي المستخدمين',
      'active_bookings': 'الحجوزات النشطة',
      'completed_today': 'اكتملت النهاردة',
      'total_revenue': 'إجمالي الأرباح',
      'currency': 'ج.م',
      'no_recent_activities': 'مفيش أي نشاطات حديثة',
      'activities_appear_here': 'النشاطات هتظهر هنا أول ما تحصل',
      'new_booking': 'حجز جديد',
      'booking_created_for': 'تم إنشاء حجز لـ',
      'booking_confirmed': 'تم تأكيد الحجز',
      'confirmed': 'تم تأكيده',
      'is_being_serviced': 'جاري العمل فيه',
      'awaiting_payment': 'في انتظار الدفع',
      'completed_waiting_payment': 'خلص وفي انتظار الدفع',
      'was_cancelled': 'تم إلغاؤه',
      'days_ago': 'أيام فاتت',
      'hours_ago': 'ساعات فاتت',
      'minutes_ago': 'دقايق فاتت',
      'just_now': 'دلوقتي حالا',
      'welcome_cashier': 'أهلاً بيك يا ',
      'pending_payments': 'مدفوعات معلقة',
      'todays_total': 'إجمالي النهاردة',
      'refunds_pending': 'مرتجعات معلقة',
      'tap_to_process_refunds': 'اضغط لمعالجة المرتجعات',
      'view_all': 'عرض الكل',
      'no_pending_payments': 'مفيش مدفوعات معلقة',
      'invoice': 'فاتورة رقم ',
      'customer': 'العميل: ',
      'amount': 'المبلغ: ',
      'completed_at': 'اكتملت: ',
      'receive': 'استلام',
      'payments_nav': 'المدفوعات',
      'profile_nav': 'البروفايل',
      'payments': 'المدفوعات',
      'pending': 'قيد الانتظار',
      'completed': 'مكتمل',
      'no_completed_payments': 'مفيش مدفوعات مكتملة',
      'receive_payment': 'استلام المبلغ',
      'cash': 'كاش',
      'card': 'كارت ائتمان',
      'digital_wallet': 'محفظة إلكترونية',
      'export_invoice': 'تصدير الفاتورة',
      'error_exporting': 'خطأ في تصدير الفاتورة: ',
      'payment_processed': 'تم الدفع بنجاح!',
      'failed_payment': 'فشل عملية الدفع',
      'booking_info': 'معلومات الحجز',
      'invoice_number': 'رقم الفاتورة',
      'vehicle': 'المركبة',
      'completion_date': 'تاريخ الانتهاء',
      'discount_code': 'كود الخصم',
      'offer_title': 'اسم العرض',
      'discount_percentage': 'نسبة الخصم %',
      'vehicle_details': 'تفاصيل المركبة',
      'make': 'الماركة',
      'model': 'الموديل',
      'year': 'السنة',
      'license_plate': 'رقم اللوحة',
      'color': 'اللون',
      'type': 'النوع',
      'vin': 'رقم الشاسيه (VIN)',
      'mileage': 'الممشى',
      'engine_type': 'نوع المحرك',
      'parts_services': 'القطع والخدمات',
      'qty': 'الكمية: ',
      'cost_breakdown': 'تفاصيل التكلفة',
      'subtotal': 'المجموع الفرعي',
      'discount': 'الخصم',
      'after_discount': 'بعد الخصم',
      'discount_applied': 'تم تطبيق الخصم',
      'code': 'الكود: ',
      'labor_cost': 'تكلفة العمالة',
      'tax': 'ضريبة (10%)',
      'total': 'الإجمالي',
      'payment_method': 'طريقة الدفع',
      'confirm_payment': 'تأكيد استلام الدفعة',
      'processing': 'جاري التنفيذ...',
      'payment_completed': 'تم الدفع',
      'request_refund': 'طلب مرتجع',
      'original_amount': 'المبلغ الأصلي: ',
      'refund_amount': 'مبلغ المرتجع',
      'reason_refund': 'سبب المرتجع *',
      'enter_reason': 'دخل سبب المرتجع',
      'submit_request': 'إرسال الطلب',
      'please_enter_reason': 'من فضلك دخل سبب المرتجع',
      'refund_submitted': 'تم إرسال طلب المرتجع بنجاح',
      'refund_processed_notified': 'تم تنفيذ المرتجع - تم إبلاغ العميل',
      'phone_not_available': 'رقم التليفون مش متاح',
      'refund_details': 'تفاصيل المرتجع',
      'amount_to_refund': 'المبلغ المراد إرجاعه',
      'processed_on': 'تم التنفيذ في ',
      'requested': 'تاريخ الطلب: ',
      'confirm_refund': 'تأكيد المرتجع',
      'confirm_refund_message': 'من فضلك أكد إنك رجعت الفلوس للعميل فعلاً.',
      'yes_refund_completed': 'أيوة، تم إرجاع المبلغ',
      'retry': 'إعادة المحاولة',
      'no_pending_refunds': 'مفيش مرتجعات قيد الانتظار',
      'close': 'إغلاق',
      'process': 'تنفيذ',
      'reason': 'السبب',
      'notes': 'ملاحظات',
      'financial_reports': 'التقارير المالية',
      'export_csv': 'تصدير CSV',
      'today': 'النهارده',
      'last_7_days': 'آخر 7 أيام',
      'last_30_days': 'آخر 30 يوم',
      'all_time': 'كل الوقت',
      'custom_range': 'فترة مخصصة...',
      'all_time_report': 'تقرير كل الوقت',
      'total_profit': 'إجمالي الربح',
      'transactions': 'العمليات',
      'margin': 'هامش',
      'creating_report': 'جاري إنشاء التقرير...',
      'file_saved': 'تم حفظ الملف',
      'csv_saved_successfully': 'تقرير CSV اتحفظ بنجاح!',
      'location': 'المكان:',
      'open_file': 'فتح الملف',
      'no_payments_found': 'مفيش عمليات دفع',
      'profit_margin': 'هامش الربح',
      'parts_cost': 'تكلفة القطع',
      'profit': 'الربح',
      'welcome_technician': 'أهلاً يا ',
      'ready_start_day': 'جاهز تبدأ يومك؟',
      'performance': 'الأداء',
      'todays_jobs': 'شغل النهارده',
      'jobs': 'الشغل',
      'ai_chat': 'دردشة الذكاء الاصطناعي',
      'my_jobs': 'شغلي',
      'no_jobs_assigned': 'مفيش شغل مخصص ليك دلوقتي',
      'assigned_jobs_appear_here': 'الشغل اللي هيتخصص ليك هيظهر هنا',
      'continue_work_complete': 'كمل الشغل وسلم العربية',
      'view_invoice': 'عرض الفاتورة',
      'start_job_add_invoice': 'ابدأ الشغل واعمل فاتورة',
      'no_status_jobs': 'مفيش عمليات مطابقة',
      'job_details': 'تفاصيل الشغل',
      'complete_job': 'تسليم الشغل',
      'started': 'وقت البدء: ',
      'completion_time': 'وقت الانتهاء: ',
      'hours_worked': 'ساعات العمل: ',
      'service_items_parts': 'الخدمات وقطع الغيار',
      'no_items_added': 'لسه مفيش بنود انضافت',
      'add_item': 'إضافة بند',
      'save_progress': 'حفظ التغييرات',
      'start_job': 'بدء الشغل',
      'job_started': 'بدأنا الشغل! بالتوفيق',
      'failed_start_job': 'فشل بدء الشغل',
      'progress_saved': 'تم حفظ التغييرات!',
      'failed_save_progress': 'فشل حفظ التغييرات',
      'please_add_item_labor': 'من فضلك ضيف بند واحد على الأقل أو تكلفة العمالة',
      'job_completed_successfully': 'تم إنهاء الشغل وتسليمه بنجاح!',
      'failed_complete_job': 'فشل إنهاء الشغل',
      'add_items_to_invoice': 'إضافة بنود للفاتورة',
      'no_catalog_items': 'مفيش بنود متاحة لنوع الصيانة ده.\nاطلب من الإدارة تضيفها.',
      'add_selected': 'إضافة المختار',
      'unit': 'قطعة',
      'could_not_load_job': 'مش عارفين نحمل تفاصيل الشغل. جرب تاني.',
      'add': 'إضافة ',
      'items_count': ' بنود',
      'profile_updated': 'تم تحديث البيانات بنجاح!',
      'error_updating_profile': 'حصل مشكلة وأحنا بنحدث البيانات: ',
      'jobs_completed': 'عمليات تمت',
      'member_since': 'عضو معانا من',
      'saving': 'بنحفظ...',
      'edit_information': 'تعديل البيانات',
      'name_required': 'الاسم مطلوب',
      'email_cannot_change': 'الإيميل مش بينفع يتغير',
      'phone_required': 'رقم الموبايل مطلوب',
      'sign_out_confirm': 'متأكد إنك عايز تخرج؟',
      'no_cars_registered': 'لسه مفيش عربيات متسجلة',
      'add_first_car': 'ضيف أول عربية ليك عشان تبدأ',
      'add_car': 'إضافة عربية',
      'car_deleted_successfully': 'تم مسح العربية بنجاح',
      'failed_delete_car': 'فشل مسح العربية',
      'delete_car_confirm': 'متأكد إنك عايز تمسح العربية دي؟',
      'add_new_car': 'إضافة عربية جديدة',
      'car_make': 'ماركة العربية',
      'select_brand': 'اختار ماركة العربية',
      'select_brand_first': 'اختار الماركة الأول',
      'select_model': 'اختار الموديل',
      'select_year': 'اختار السنة',
      'select_color': 'اختار اللون',
      'car_type': 'نوع العربية',
      'sedan': 'سيدان',
      'suv': 'SUV / جيب',
      'truck_pickup': 'نقل / بيك أب',
      'hatchback': 'هاتشباك',
      'coupe': 'كوبيه',
      'van_minivan': 'فان / ميني فان',
      'plate_number': 'نمرة العربية',
      'plate_number_hint': 'مثال: 123 أ ب ج',
      'car_added_successfully': 'العربية انضافت بنجاح!',
      'failed_add_car': 'فشل إضافة العربية',
      'select_brand_validation': 'من فضلك اختار الماركة',
      'select_model_validation': 'من فضلك اختار الموديل',
      'select_year_validation': 'من فضلك اختار السنة',
      'select_color_validation': 'من فضلك اختار اللون',
      'enter_plate_validation': 'من فضلك دخل نمرة العربية',
      'my_bookings': 'حجوزاتي',
      'no_bookings_yet': 'لسه مفيش حجوزات',
      'book_first_service': 'احجز أول صيانة ليك دلوقتي',
      'cancel_booking': 'إلغاء الحجز',
      'cancel_booking_confirm': 'متأكد إنك عايز تلغي الحجز ده؟',
      'booking_cancelled': 'تم إلغاء الحجز',
      'failed_cancel_booking': 'فشل إلغاء الحجز',
      'select_your_car': 'اختار عربيتك',
      'add_another_car': 'إضافة عربية تانية',
      'maintenance_type': 'نوع الصيانة',
      'appointment_date_time': 'ميعاد الحجز',
      'working_hours_desc': 'مواعيد العمل: السبت – الخميس، 8:00 ص – 6:00 م',
      'select_date': 'اختار التاريخ',
      'select_time': 'اختار الوقت',
      'additional_notes': 'ملاحظات إضافية (اختياري)',
      'describe_issue_hint': 'اشرح المشكلة اللي عندك بالتفصيل...',
      'confirm_booking': 'تأكيد الحجز',
      'back': 'رجوع',
      'next': 'التالي',
      'your_car': 'عربيتك',
      'service': 'الخدمة',
      'confirm': 'تأكيد',
      'select_car_validation': 'من فضلك اختار عربيتك الأول',
      'select_maintenance_validation': 'من فضلك اختار نوع الصيانة',
      'select_date_time_validation': 'من فضلك اختار التاريخ والوقت',
      'closed_fridays': 'إحنا أجازة يوم الجمعة',
      'booking_confirmed_success': 'تم تأكيد الحجز بنجاح!',
      'select_date_first': 'من فضلك اختار التاريخ الأول',
      'working_hours_help': 'مواعيد العمل: 8:00 ص – 6:00 م',
      'select_time_range_validation': 'من فضلك اختار وقت بين 8:00 ص و 6:00 م',
      'enter_discount_code': 'من فضلك دخل كود الخصم',
      'select_date_help': 'اختار ميعاد الحجز (الجمعة أجازة)',
      'booking_summary': 'ملخص الحجز',
      'final_price_notice': 'السعر النهائي بيتحدد بعد ما الفني يخلص الصيانة',
      'discount_code_hint': 'دخل الكود (اختياري)',
      'apply': 'تطبيق',
      'discount_applied_desc': 'خصم تم تطبيقه',
      'view_available_offers': 'عرض العروض المتاحة',
      'regular_maintenance_hint': 'زيت، فلاتر، سوايل...',
      'inspection_hint': 'فحص أمان، كشف كمبيوتر...',
      'repair_hint': 'فرامل، موتور، فتيس...',
      'emergency_hint': 'عطل طارئ - إنقاذ طريق...',
      'service_history': 'سجل الخدمات',
      'total_spent': 'إجمالي المصاريف',
      'no_service_history': 'مفيش سجل خدمات',
      'service_history_desc': 'سجل الخدمات اللي عملتها هيظهر هنا',
      'total_cost_label': 'إجمالي التكلفة:',
      'your_rating': 'تقييمك: ',
      'rate_this_service': 'قيم الخدمة دي',
      'rating_submitted': 'تم تقديم التقييم بنجاح!',
      'failed_rating': 'فشل تقديم التقييم',
      'invoice_details': 'تفاصيل الفاتورة',
      'booking_id': 'رقم الحجز: ',
      'download_pdf': 'تحميل PDF',
      'add_car_subtitle': 'سجل عربيتك دلوقتي',
      'book_service': 'احجز صيانة',
      'book_service_subtitle': 'حدد ميعاد صيانتك',
      'ai_assistant': 'مساعد ذكي',
      'ai_assistant_subtitle': 'اسأل أي سؤال',
      'special_offers': 'عروض خاصة',
      'special_offers_subtitle': 'شوف الخصومات والعروض',
      'service_history_subtitle': 'شوف الصيانات اللي عملتها',
      'my_cars_subtitle': 'تحكم في عربياتك',
      'cancel_appointment': 'إلغاء الميعاد',
      'keep_appointment': 'خلي الميعاد زي ما هو',
      'appointment_cancelled_success': 'تم إلغاء الميعاد بنجاح',
      'failed_cancel_appointment': 'فشل إلغاء الميعاد، من فضلك حاول تاني',
      'cancel_appointment_confirm': 'متأكد إنك عايز تلغي الميعاد ده؟ الخطوة دي مش هينفع ترجع فيها تاني.',
      'missed_appointments': 'مواعيد فاتتك',
      'missed_appointments_desc': 'المواعيد دي فاتتك، من فضلك حدد ميعاد جديد أو إلغي الميعاد.',
      'reschedule': 'تغيير الميعاد',
      'missed_status': 'فايت',
      'was_scheduled': 'كان ميعادك: ',
      'missed_ago': 'فات عليه ',
      'days_only': 'أيام',
      'day_only': 'يوم',
      'hours_only': 'ساعات',
      'hour_only': 'ساعة',
      'recently': 'من شوية',
      'offers_announcements': 'العروض والتنبيهات',
      'announcements': 'تنبيهات',
      'discounts': 'خصومات',
      'promotions': 'عروض ترويجية',
      'news': 'أخبار',
      'no_offers_available': 'مفيش عروض متاحة',
      'check_back_later_offers': 'خليك متابع عشان العروض الجديدة!',
      'error_loading_offers': 'حصل مشكلة وأحنا بنحمل العروض',
      'valid_from': 'صالح من',
      'expires': 'بينتهي في',
      'valid_period': 'فترة الصلاحية:',
      'terms_conditions': 'الشروط والأحكام:',
      'code_label': 'الكود: ',
      'enter_code_booking_desc': 'دخل الكود ده وأنت بتحجز عشان تاخد الخصم',
      'discount_off': 'خصم',
      'no_offers_type': 'مفيش عروض من النوع ده',
      'profile_updated_success': 'تم تحديث البيانات بنجاح!',

      'light': 'فاتح',
      'dark': 'غامق (دارك مود)',
      'system': 'زي الجهاز',

      'code_deactivated_users_disabled': 'تم إلغاء الكود وتعطيل حسابات المستخدمين',
      'code_activated_users_enabled': 'تم تفعيل الكود وتفعيل حسابات المستخدمين',
      'not_used_yet': 'لم يتم استخدامه بعد',
      'error_loading_names': 'مشكلة في تحميل الأسماء',
      'delete_invite_code': 'حذف كود الدعوة',
      'delete_code_confirm': 'متأكد إنك عايز تحذف الكود ده: ',
      'code_deleted_success': 'تم حذف الكود بنجاح',
      'error_deleting_code': 'حصل مشكلة وأحنا بنحذف الكود: ',
      'deactivate': 'تعطيل',
      'activate': 'تفعيل',
    }
  };
}

extension LocalizationHelper on String {
  String tr(WidgetRef ref) {
    final locale = ref.watch(localeProvider);
    final currentLang = locale.languageCode;
    return AppLocalizations.translations[currentLang]?[this] ?? this;
  }
}
